{% set version = '3.8.1' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-gtools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/gtools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/gtools/gtools_{{ version }}.tar.gz
  sha256: 051484459bd8ad1b03425b8843d24f6828fea18f7357cfa1c192198cc3f4ba38

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base

  run:
    - r-base
    - {{native}}gcc-libs         # [win]

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('gtools')"           # [not win]
    - "\"%R%\" -e \"library('gtools')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: https://CRAN.R-project.org/package=gtools
  license: GPL-2
  summary: 'Functions to assist in R programming, including: - assist in developing, updating,
    and maintaining R and R packages (''ask'', ''checkRVersion'', ''getDependencies'',
    ''keywords'', ''scat''), - calculate the logit and inverse logit transformations
    (''logit'', ''inv.logit''), - test if a value is missing, empty or contains only
    NA and NULL values (''invalid''), - manipulate R''s .Last function (''addLast''),
    - define macros (''defmacro''), - detect odd and even integers (''odd'', ''even''),
    - convert strings containing non-ASCII characters (like single quotes) to plain
    ASCII (''ASCIIfy''), - perform a binary search (''binsearch''), - sort strings containing
    both numeric and character components (''mixedsort''), - create a factor variable
    from the quantiles of a continuous variable (''quantcut''), - enumerate permutations
    and combinations (''combinations'', ''permutation''), - calculate and convert between
    fold-change and log-ratio (''foldchange'', ''logratio2foldchange'', ''foldchange2logratio''),
    - calculate probabilities and generate random numbers from Dirichlet distributions
    (''rdirichlet'', ''ddirichlet''), - apply a function over adjacent subsets of a
    vector (''running''), - modify the TCP\_NODELAY (''de-Nagle'') flag for socket objects,
    - efficient ''rbind'' of data frames, even if the column names don''t match (''smartbind''),
    - generate significance stars from p-values (''stars.pval''), - convert characters
    to/from ASCII codes (''asc'', ''chr''), - convert character vector to ASCII representation
    (''ASCIIfy'').'

  license_family: GPL2

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: gtools
# Title: Various R Programming Tools
# Description: Functions to assist in R programming, including: - assist in developing, updating, and maintaining R and R packages ('ask', 'checkRVersion', 'getDependencies', 'keywords', 'scat'), - calculate the logit and inverse logit transformations ('logit', 'inv.logit'), - test if a value is missing, empty or contains only NA and NULL values ('invalid'), - manipulate R's .Last function ('addLast'), - define macros ('defmacro'), - detect odd and even integers ('odd', 'even'), - convert strings containing non-ASCII characters (like single quotes) to plain ASCII ('ASCIIfy'), - perform a binary search ('binsearch'), - sort strings containing both numeric and character components ('mixedsort'), - create a factor variable from the quantiles of a continuous variable ('quantcut'), - enumerate permutations and combinations ('combinations', 'permutation'), - calculate and convert between fold-change and log-ratio ('foldchange', 'logratio2foldchange', 'foldchange2logratio'), - calculate probabilities and generate random numbers from Dirichlet distributions ('rdirichlet', 'ddirichlet'), - apply a function over adjacent subsets of a vector ('running'), - modify the TCP\_NODELAY ('de-Nagle') flag for socket objects, - efficient 'rbind' of data frames, even if the column names don't match ('smartbind'), - generate significance stars from p-values ('stars.pval'), - convert characters to/from ASCII codes ('asc', 'chr'), - convert character vector to ASCII representation ('ASCIIfy').
# Version: 3.8.1
# Date: 2018-06-19
# Author: Gregory R. Warnes, Ben Bolker, and Thomas Lumley
# Maintainer: Gregory R. Warnes <greg@warnes.net>
# License: GPL-2
# Depends: methods, stats, utils
# NeedsCompilation: yes
# Packaged: 2018-06-25 14:51:36 UTC; gwarnes
# Repository: CRAN
# Date/Publication: 2018-06-26 14:37:57 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
