# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "iFCM+j4xjkMl6a1vIiFNWtfP+KpuQrKo71PFjhyQSLKzsP9zpJVYIt4Cq/HFJE4lqw05iEWc1FGu4Gw+Ci0iPQUiGnArzmgExse9Gcmd0Z/A29X3QP3XOMCObDFVEUwqCK3EFdSIKuJHzXDbxsaG253nmOBw/OeiLSgxf/MYr10wfS11ZCXYeVYW0u7pLwEOkttkD7IypFrVsOhr9fPMa3vq3/wug0qCcXziXn7YQSYN9kJOsbfMO5enCSwPM6VzjcCW65kTImmxFbFive7ev4k643hwVrFbWZETXlLM+r2CTV00Xa6AOjau8c09YBd9mMKUzJKsVT/n7uVKzTX6DG39xMd0VR+MifTJXn0lCcd61PlP84Z6SCC23W/Dwd/t60946kOjFLLbvJdPL4NQRcB88/BXnYvanl3RIe2Aqe8/D31PTxRYbBqiJivfqdYzhfCgkyZ6F+96nXB0lDA4vJRqQYocnpYj6+p5iEU1AbJ90ak6YO62pgOINiBfTb1kdgK7q0KXqbotYXow+JtnnokQRVH+QzBPOlI6pU0nUA1wptSSIohfxwH+BjOcVYIFi8QaQ8gdq7vJmoXpHh37EJ2RDdBAX7lR/h/UgpgweQUI4ZPHC9cQiDWeJkSVwKY+nrns4osPKwOJN3HVfeE/Jd8SILzrFOhuYSDNFO5xGhw="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
