travis:
  secure:
    BINSTAR_TOKEN: p83fkzqQaAJUjx5BRPDVCk+4p88GJQuGtWmK/uYPTQFO8Op/LI/p6eZS7dNx5WBvqIU8DEY7UGk5anUTvGQv7njVbMWj/XxFAZLnY71Hbttckw6v6CBFNJIThagqsn8UV53wZP+cUeGQ8X7Glofgm70GVvDdIGWVLbqA2R8Efk7/CwlMxdPZs1DB8zshyjV/k9V43O0DNXBnY5dZyyQJNt87XcAoB5b2ikpxkrJHOfK3GAMPQsH37n5zXM639aRtuVHShduGef5MX4qHd5fngg/VyWPVwh3u9ySJtWy9ZIg2nEJC39c7U3lhzWIxbxEXVBpDA1A6HBnuorDcuCsh8eK6utQFOpcEJjY86c6ktwBFPPJr/vTowXRSIJxQa81cpVYk7VrK/nY7zp5QkPiETQIvvmTHvy9eJKo8TsdES4XTftb1tjRMlp9hujNguTzwmh7G8HCIcUlAAzeGYYNDJdG7tbml821VLpZ+Qaz+wApDTxjrVZgJpDCrHzaBEiJKFbzGItjRZW1RZE63BcGWXDNjY5zx7Krd8PKoj45WbYPrvqKMlJBthkrv7SogsZtudmdolrk9SygY41b34KhnAgzFVyr3/tXPb9+kgn2l7//EG0QjVDoDK3A/+7wZAdnaqqAv5puBhijJbSsUKe39ISrqoxXuAT+okPGI4prU5Z0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
