travis:
  secure:
    BINSTAR_TOKEN: iyW7H/pYiv3FEYdqZBH9AA4CU3pGunQbNFquMvcN4Bk528fHrGq7saif9q6mE/lBdk2UcDAA1EOsW1z8pMzMRTy6noHIrjJiRmSab5Ia2EbKkQi5UVPolADfHr7E2Z3XUbdundgm03YKynyHBIAQ83Cz9ORsURFEFUqSw9SAN/pvv+9T9vzHQ5BOi+7CYTagloGB0Pfgh+BuawCnum0VGOJOmYHmon7yd2vSObH+67zVLGZUs9vVAJYElvgxdRmP7n92ZC353DcqPH3RpY3T0vfHmSbNhVVtJNgssUUZsSWEIb7Oz1e4RoCXjD8HD2Fes4WRFZ+4zfQLWxUHWytQM0p7FR3yNs3zIwa9VfF4aZMAakAVqqFnt6wfvX5r+vEeiuW5ld7RaO1b/nUSj8JLTs57LWcfiNI7g9/i/iBkE1PDpiBsg1Or+ahFMFbH9PSPIFHGTDsgJlRtFi3LceaOm+X/j2641fOqcTbGMajN4yoRtzAv9SYqWVGK5Nh0Hy4Vjjz1XTDGxeQH+n8r9DHmixhcCd5P9/Vq4+iVJOhXeO6u6qqHgIVZ3jJx90zwfkkirBxFFK5Ng5ivpgVZlrWHMZrWWJrvcMbI6EX1CB3hITaaizbQzs5VDj3nAthH9FuR1Bq1wDtp9qbzeVBTWJ22WzGel/eSv7KTxI7YxZ9aAps=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
