travis:
  secure:
    BINSTAR_TOKEN: j6iqMRHoWQ/Y5j1USPtppWrqiJ488H+BVtPAqA+iLcivz+hL1eIRADsdsKHOIk5vY3Ud1GI6+UNEhj0YzAwFN3rYs4IgefttVW7Z/fvOkT2wfQoCr8gxPyZh/orQFDQEmrjxT5NaPyP3p0pbD9TVnojE+vlO3THLzNZY2XbeiIGenxRKkV0zVUrAdE5bYoVAaXHwTbwAzJRgW48o4Px6Ln/UECkfmduEUkN6jFV4F/ch8JfhDL3D0mlbXsp1VnCo5UspQQBorG3/OnZKn/SxQSkFDG9TdC18dp19+2AJ+8pB+9+CPgTid5RUqCss8pEFc5g3RyxF2Q4okzpg6BzLIJiAYvO36lRfkeSK7USv7E59rgl2ZdtFZxQwQWnqIdFfRolrHKYeE7HH4RDS7snRb8Jc1PDEfADjjR93NyA9AQTNURKP8Wz2U7afDmmvO0JEEje1SzKTrjL2VrCw8uefAP+A4i0ns1omEA4dr9anbJyh3t6LmVB2d0Ooq5mNQ9Qosum5bQp/rx918BqUGCgPxezEsDbddfLde1UJmdKf4zb/TPprPyBjcqrINSv1CQH9bxthvHRFD2UNTFkntV9wQFGEOmfW4j2HH/AGfLTPpkoA3tM09XMmQaF8KL4Zr9AJQ+D7yv5eH15TbLAfr5QgK/H9EoJ7lhNBQ3X0ygv9ZDg=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
