travis:
  secure:
    BINSTAR_TOKEN: P3xg2tjEzw4RzoJA4s/KjYBToSzZFXbbEPV9yg2Mw9qtufheBUPvZmz1k02e6aeVCcCVRW8xJgt8ml3I9UcizIEVJj+Gj5/HX6HL09KIxXSBsx1I/WDqQluW0GEJxurIMLK8VAWr7FT7kl8MwNY3cFd+6EJrSBsMqFKF5YLYj/UjrWuiQ8p4Ya+V4b3EnanUAYE3O4AiqeahRi5FjU8B+o/I8/1+/vyeWqwLbXnxVSv4ZhgV037ZYMlwW4NvqacdkQ1YUYpI6iUQO+mNtW/A05UqB5N+GbMkH2xT2T2BTXmJOoupunFssI+iXCjRLS4gigN1USTGZYqJ11GKpliJ4pKQB6YVrINYSkD02ifeyy3xXQkk0M8BKa/YnOBNNk5yh28biYdbEG92RmkoLantd0Z93uocPCfgLLbpfNGgxIItYqmatJ5r7dzzkn+khghgYVpOD6/fAB53Idwx04YYMoHP3Ro7hADAjsgKu8aNmI3tUsj22iQRgUo0OVRRYjBtYgoIaLxUmVJVBk/Z4UoYyIEijFnII8SGocVE4zTAvl5eml9xiG47OaIEmy3a7Hu2jUof+WEEIXBZP6KZs3S56rTXzIR8clgchCt44QPyJrSghcVsncmktqxO1+xp3gKlzbhGT4oxqM26w77+tMpCEiZe6tDftqHlnBDFOy6s50s=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
